### ISSUE TITLE
AssertionError: assert hasattr(self, "_row_class") (EncLog)

### ISSUE THREAD

**Issue by williballenthin** [malwarefrank/dnfile#22]
encountered an unexpected exception when parsing the file 0033ca037e0496c5c33e3dc19714fb3e:

```
❯ python foo.py tests/data/0033ca037e0496c5c33e3dc19714fb3e
Traceback (most recent call last):
...
  File "scripts/print_cil.py", line 29, in main
    pe = dnfile.dnPE(args.path)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 61, in __init__
    super().__init__(name, data, fast_load)
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 2743, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 129, in __parse__
    super().__parse__(fname, data, fast_load)
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 3148, in __parse__
    self.full_load()
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 3259, in full_load
    self.parse_data_directories()
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 174, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 219, in parse_clr_structure
    return ClrData(self, rva, size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 481, in __init__
    self.metadata = ClrMetaData(pe, metadata_rva, metadata_size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 346, in __init__
    s.parse(self.streams_list)
  File "/home/user/code/dnfile/src/dnfile/stream.py", line 375, in parse
    table = mdtable.ClrMetaDataTableFactory.createTable(
  File "/home/user/code/dnfile/src/dnfile/mdtable.py", line 2031, in createTable
    table = cls._table_number_map[number](
  File "/home/user/code/dnfile/src/dnfile/base.py", line 542, in __init__
    assert hasattr(self, "_row_class")
AssertionError
```

**Comment by williballenthin** [comment]
debugging details:

![image](https://user-images.githubusercontent.com/156560/146261343-7f1d009c-02e9-479f-9695-0cc72071c0a1.png)

so the file has an instance of table 30/0x2E

which dnfile maps to `Unused30` here:
https://github.com/malwarefrank/dnfile/blob/master/src/dnfile/mdtable.py#L1995

and `Unused30` doesn't have an associated row class:

https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/mdtable.py#L1281-L1283

**Comment by williballenthin** [comment]
but what is table 30?

CFF explorer identifies it as `ENCLog`:
![image](https://user-images.githubusercontent.com/156560/146261746-4bc0d56d-a4bf-4e1d-8028-3f34c23623ee.png)

and dnlib also:
https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/MD/Table.cs#L68-L71

and M$ here:
![image](https://user-images.githubusercontent.com/156560/146261998-b7a3ac7f-fe9d-44b9-af75-2b8f16185a0f.png)
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.ecma335.tableindex?view=net-6.0
