### ISSUE TITLE
AssertionError: assert hasattr(self, "_row_class") (FieldPtr)

### ISSUE THREAD

**Issue by williballenthin** [malwarefrank/dnfile#27]
when parsing a private sample, we encounter an exception like:

```
❯ python -m pdb -- ./examples/dndump.py <redacted>
Traceback (most recent call last):
  File "/usr/lib/python3.8/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/usr/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/user/code/dnfile/examples/dndump.py", line 2, in <module>
    '''
  File "/home/user/code/dnfile/examples/dndump.py", line 320, in main
    dn = dnfile.dnPE(args.input)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 61, in __init__
    super().__init__(name, data, fast_load)
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 2743, in __init__
    self.__parse__(name, data, fast_load)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 129, in __parse__
    super().__parse__(fname, data, fast_load)
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 3148, in __parse__
    self.full_load()
  File "/home/user/env/lib/python3.8/site-packages/pefile.py", line 3259, in full_load
    self.parse_data_directories()
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 174, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 219, in parse_clr_structure
    return ClrData(self, rva, size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 481, in __init__
    self.metadata = ClrMetaData(pe, metadata_rva, metadata_size)
  File "/home/user/code/dnfile/src/dnfile/__init__.py", line 346, in __init__
    s.parse(self.streams_list)
  File "/home/user/code/dnfile/src/dnfile/stream.py", line 336, in parse
    table = mdtable.ClrMetaDataTableFactory.createTable(
  File "/home/user/code/dnfile/src/dnfile/mdtable.py", line 2091, in createTable
    table = cls._table_number_map[number](
  File "/home/user/code/dnfile/src/dnfile/base.py", line 542, in __init__
    assert hasattr(self, "_row_class")
AssertionError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/user/code/dnfile/src/dnfile/base.py(542)__init__()
-> assert hasattr(self, "_row_class")
(Pdb) self
<dnfile.mdtable.FieldPtr object at 0x7fba4852a460>
(Pdb) self.name
'FieldPtr'
(Pdb) self.number
3
(Pdb)
```

**Comment by williballenthin** [comment]
`FieldPtr` is not implemented:

https://github.com/malwarefrank/dnfile/blob/1cc7db2f8cb5a4eeb72fbe557f5506c1ce852770/src/dnfile/mdtable.py#L221-L224

**Comment by williballenthin** [comment]
dnlib implementation: https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/MD/RawTableRows.cs#L110
https://github.com/0xd4d/dnlib/blob/4e0837cb0f4319ffbcdd1642d1973fce203b2177/src/DotNet/MD/TablesStream_Read.cs#L81-L91
https://github.com/0xd4d/dnlib/blob/873ba1a77e58a5d60767c66ce9e55f442fbdfff5/src/DotNet/MD/DotNetTableSizes.cs#L150-L152

M$ implementation: https://github.com/dotnet/coreclr/blob/master/src/inc/metamodelpub.h#L157-L165
