### ISSUE TITLE
Problems with strings extractions

### ISSUE THREAD

**Issue by doomedraven** [malwarefrank/dnfile#47]
Hello, I just got this bug when i was trying to list the strings

```
pip3 install git+https://github.com/malwarefrank/dnfile -U
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting git+https://github.com/malwarefrank/dnfile
  Cloning https://github.com/malwarefrank/dnfile to /private/var/folders/yt/mbh1wxlj6fq0qqxbjnjfqr200000gn/T/pip-req-build-efg5499r
  Running command git clone --filter=blob:none --quiet https://github.com/malwarefrank/dnfile /private/var/folders/yt/mbh1wxlj6fq0qqxbjnjfqr200000gn/T/pip-req-build-efg5499r
  Resolved https://github.com/malwarefrank/dnfile to commit 92847841e6496453598947a74eb78fa7299ad579
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pefile>=2019.4.18 in /usr/local/lib/python3.9/site-packages (from dnfile==0.10.0) (2021.9.3)
Requirement already satisfied: future in /usr/local/lib/python3.9/site-packages (from pefile>=2019.4.18->dnfile==0.10.0) (0.18.2)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

* dnstring.py is https://github.com/malwarefrank/dnfile/blob/master/examples/dnstrings.py

```
➜ python3 dnstring.py b9efc289ffd8951a65f66ddf2649c1959ad1b94f1177002b20f05e8ae86853ae
reference to missing table: File
reference to missing table: File
Traceback (most recent call last):
  File "<censured>/dnstring.py", line 42, in <module>
    show_strings(fname)
  File "<censured>/dnstring.py", line 33, in show_strings
    s = dnfile.stream.UserString(buf)
  File "/usr/local/lib/python3.9/site-packages/dnfile/stream.py", line 116, in __init__
    self.value: str = data.decode(encoding)
UnicodeDecodeError: 'utf-16-le' codec can't decode byte 0x00 in position 28: truncated data
```

im not sure how string can be 29bytes in wide mode
```
'utf-16-le' codec can't decode byte 0x00 in position 28: truncated data b'S\x00t\x00u\x00b\x00.\x00R\x00e\x00s\x00o\x00u\x00r\x00c\x00e\x00s\x00\x00'
```

any ideaa?

thank you

**Comment by williballenthin** [comment]
See the comment here that explains what I found when I dug into a similar issue:

https://github.com/malwarefrank/dnfile/pull/21#issuecomment-1098269419

notably:

> For instance, .NET (and the C# compiler) allow strings to have unpaired UTF-16 surrogates. Dotfuscator's knowledge of this fact results in scenarios in protected code similar to the minimal repro: an ill-formed UTF-16 string constant is passed to one method, which returns a well-formed UTF-16 string (only known at runtime) for use in reflection.

and more details here: https://codeblog.jonskeet.uk/2014/11/07/when-is-a-string-not-a-string/

**Comment by doomedraven** [comment]
thank you

**Comment by williballenthin** [comment]
if you make updates locally to `dnstrings.py` @doomedraven would you consider contributing them back here?
